mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('purplegorilla.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

purplegorilla/urls.py
from django.urls import path
from . import views  # Import views to connect routes to view functions

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('products', views.index, name='product-index'),
    path('user/<int:user_id>', views.user, name='user'),
    path('product/create', views.ProductCreate.as_view(), name="product-create"),
    path('product/<int:pk>/update',
         views.ProductUpdate.as_view(), name="product-update"),
    path('products/<int:pk>/delete/',
         views.ProductDelete.as_view(), name='product-delete'),
    path('product/<int:product_id>', views.product_detail, name="product-detail"),
    path('order/<int:product_id>', views.confirm_order, name="order-confirm"),
    path('order/<int:pk>/update',
         views.OrderUpdate.as_view(), name="order-update"),
    path('order/<int:pk>/delete', views.OrderDelete.as_view(), name="order-delete"),
    path('order/<int:order_id>/detail', views.order_detail, name="order-detail"),
    path('order/create/<int:user_id>/<int:product_id>',
         views.order_create, name="order-create"),
    path('accounts/signup/', views.signup, name='signup'),
]

purplegorilla/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from decimal import Decimal


class Product(models.Model):
    CATEGORIES = (
        ('G', 'Generic'),
        ('E', 'Electronics'),
        ('F', 'Fashion'),
        ('HF', 'Home and Furnitures'),
        ('BH', 'Beauty and Health'),
        ('BM', 'Books and Media'),
        ('SO', 'Sports and Outdoor'),
        ('TB', 'Toys and Baby Products'),
        ('FB', 'Food and Beverages')
    )
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(max_length=250)
    category = models.CharField(
        max_length=2,
        choices=CATEGORIES,
        default=CATEGORIES[0][0]
    )
    image = models.CharField(
        max_length=250,
        default='https://i.imgur.com/DTQfCw5.png'
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product-index')

    def total_before_tax(self):
        return self.price + 10

    def estimated_tax(self):
        tax_rate = Decimal('0.06')
        return (self.price + 10) * tax_rate

    def total_price(self):
        tax_rate = Decimal('0.06')
        return self.price + 10 + (self.price + 10) * tax_rate


class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Shipped', 'Shipped'),
        ('Delivered', 'Delivered'),
        ('Cancelled', 'Cancelled'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=20,
        choices=STATUS,
        default='Pending'
    )
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Order {self.id} by {self.user.username}"

    def get_absolute_url(self):
        return reverse('user', kwargs={'user_id': self.user_id})

purplegorilla/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.urls import reverse
from django.db.models import Q
from .models import Product, Order
from decimal import Decimal
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Run this command to seed the database: python3 manage.py seed --mode=refresh
# Run this command to delete all products in database: python3 manage.py seed --mode=clear

@login_required
def order_create(request, user_id, product_id):
    product = Product.objects.get(id=product_id)
    product.status = True
    product.save()

    # Create the order and save it, status = pending
    order = Order.objects.create(
        user=request.user, product=product, total_price=Decimal(product.total_price()))
    return redirect('user', user_id=user_id)


@login_required
def order_detail(request, order_id):
    order = Order.objects.get(id=order_id)
    return render(request, 'orders/detail.html', {'order': order})


@login_required
def confirm_order(request, product_id):
    product = Product.objects.get(id=product_id)
    return render(request, 'orders/confirm_order.html', {'product': product})


class OrderUpdate(LoginRequiredMixin, UpdateView):
    model = Order
    fields = ['status']

    def get_success_url(self):
        order = self.object
        return reverse('user', kwargs={'user_id': order.product.user.id})


class OrderDelete(LoginRequiredMixin, DeleteView):
    model = Order

    def get_success_url(self):
        user_id = self.object.user.id
        product = self.object.product
        product.status = False
        product.save()

        return reverse('user', kwargs={'user_id': user_id})


@login_required
def index(request):
    products = Product.objects.filter(status=False)
    product_name = request.GET.get('product_name')
    product_category = request.GET.get('category')
    if product_name != '' and product_name is not None:
        products = Product.objects.filter(
            name__icontains=product_name, status=False)

    if product_category != '' and product_category is not None:
        products = Product.objects.filter(
            category=product_category, status=False)

    return render(request, 'purplegorilla/index.html', {'products': products})


@login_required
def user(request, user_id):
    # get orders that belongs to the buyer and also associated with the seller
    orders = Order.objects.filter(
        Q(user_id=user_id) | Q(product__user_id=user_id))
    products = Product.objects.filter(user_id=user_id)

    product_name = request.GET.get('product_name')
    product_category = request.GET.get('category')
    if product_name != '' and product_name is not None:
        products = Product.objects.filter(
            name__icontains=product_name, status=False, user_id=user_id)

    if product_category != '' and product_category is not None:
        products = Product.objects.filter(
            category=product_category, status=False, user_id=user_id)

    return render(request, 'user.html', {'products': products, 'orders': orders})


class ProductCreate(LoginRequiredMixin, CreateView):
    model = Product
    fields = ['name', 'image', 'description', 'category', 'price']

    def form_valid(self, form):
        # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user
        # form.instance is the product
        # Let the CreateView do its job as usual
        return super().form_valid(form)


class ProductUpdate(LoginRequiredMixin, UpdateView):
    model = Product
    fields = ['name', 'image', 'description', 'category', 'price']


class ProductDelete(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = '/products'


@login_required
def product_detail(request, product_id):
    product = Product.objects.get(id=product_id)
    return render(request, 'products/detail.html', {'product': product})


def signup(request):
    # Handle the POST request
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('product-index')
        else:
            error_message = 'Invalid sign up - try again'
    # Handle the GET request (render the form)
    form = UserCreationForm()
    return render(request, 'signup.html', {'form': form, 'error_message': error_message})


class Home(LoginRequiredMixin, LoginView):
    template_name = 'home.html'

purplegorilla/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% load form_tags %}

{% block head %}
{% endblock %}

{% block content %}
{% if not user.is_authenticated %}
    {% if form.errors %}
        {% for field, errors in form.errors.items %}
            {% for error in errors %}
                <div class="alert alert-danger mx-auto w-50 mt-3" role="alert">{{ error }}</div>
            {% endfor %}
        {% endfor %}
    {% endif %}
    <section class='w-25 mx-auto mt-5 border rounded p-4'>
        <form action="{% url 'home' %}" method="post" class="login">
            <h1 class='text-center'>Login</h1>
            {% csrf_token %} 
            <div class="mb-3">
                <label for="id_username" class="form-label">Username</label>
                {{ form.username|add_class:"form-control" }}
            </div>
            <div class="mb-3">
                <label for="id_password" class="form-label">Password</label>
                {{ form.password|add_class:"form-control" }}
            </div>
            <input type="hidden" name="next" value="{{ next }}" />
            <button type="submit" class="btn btn-outline-success w-100 submit">Login</button>
        </form>
    </section>
{% else %}
    <div class="display-1 text-center">Welcome to Kong's Market</div>
    <div class="w-100 d-flex justify-content-center">
        <img src="{% static 'images/gorilla.png' %}" alt="Logo">
    </div>
    <div class="links d-flex justify-content-center py-3">
        <a class="btn btn-outline-primary w-25 m-1" href="{% url 'product-index'%}">Swing into Savings!</a>
    </div>
    <div class="slider mx-auto">
        <div class="slide active">
          <h1 class="animated-text">Shop like a Trillionaire!</h1>
        </div>
        <div class="slide">
          <h1 class="animated-text">Free Returns Within 90 days</h1>
        </div>
        <div class="slide">
          <h1 class="animated-text">Price Adjustment Within 30 days</h1>
        </div>
    </div>
{% endif %}
{% endblock %}

purplegorilla/templates/orders/confirm_order.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{% endblock %}

{% block content %}

{% if user.is_authenticated %}
    <div class="container mx-auto d-flex flex-column justify-content-center align-items-center p-3">
      <h1>Order Confirmation</h1>
      <div class="card mb-3 w-50">
          <div class="row g-0">
            <div class="col-md-4 d-flex flex-column justify-content-center align-items-center p-1">
              <img src="{{product.image}}" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">Name: {{product.name}}</h5>
                <p class="card-text"> Price: {{product.price}}</p>
                <p class="card-text"> Description: {{product.description}}</p>
                <p class="card-text"><small class="text-body-secondary">Sold by: {{product.user.username}}</small></p>
              </div>
            </div>
          </div>
      </div>
      <h1>Order Summary</h1>
      <table class="table w-50">
          <tbody>
            <tr>
              <td>Items:</td>
              <td>${{product.price}}</td>
            </tr>
            <tr>
              <td>Shipping and Handling:</td>
              <td>$10.00</td>
            </tr>
            <tr>
              <td>Total before Tax:</td>
              <td>${{product.total_before_tax|floatformat:2}}</td>
            </tr>
            <tr>
              <td>Estimated tax to be collected:</td>
              <td>${{ product.estimated_tax|floatformat:2 }}</td>
            </tr>
            <tr>
              <td class='h3'>Order Total:</td>
              <td class='h3'>${{product.total_price|floatformat:2}}</td>
            </tr>
          </tbody>
      </table>
      <a class='btn btn-outline-warning w-50' href={% url 'order-create' user.id product.id %}>Place your Order</a>
    </div>
{% endif %}
{% endblock %}

purplegorilla/templates/orders/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{% endblock %}

{% block content %}
<div class="container mx-auto d-flex flex-column justify-content-center align-items-center p-3">
    <h1>Order Details</h1>
    <div class="card mb-3 w-75">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="{{order.product.image}}" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">Name: {{order.product.name}}</h5>
              <p class="card-text"> Price: {{order.product.price}}</p>
              <p class="card-text"> Description: {{order.product.description}}</p>
              <p class="card-text"><small class="text-body-secondary">Sold by: {{order.product.user.username}}</small></p>
            </div>
          </div>
        </div>
    </div>
    <h1>Order Summary</h1>
    <table class="table w-75">
        <tbody>
          <tr>
            <td>Items:</td>
            <td>${{order.product.price}}</td>
          </tr>
          <tr>
            <td>Shipping and Handling:</td>
            <td>$10.00</td>
          </tr>
          <tr>
            <td>Total before Tax:</td>
            <td>${{oder.product.total_before_tax|floatformat:2}}</td>
          </tr>
          <tr>
            <td>Estimated tax to be collected:</td>
            <td>${{order.product.estimated_tax|floatformat:2 }}</td>
          </tr>
          <tr>
            <td class='h3'>Order Total:</td>
            <td class='h3'>${{order.product.total_price|floatformat:2}}</td>
          </tr>
        </tbody>
    </table>
    <h1>Order Status: {{order.status}}</h1>
    <a class='btn btn-outline-danger w-75' href={% url 'order-delete' order.id %}>Cancel Order</a>
  </div>
{% endblock %}

purplegorilla/templates/products/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{% endblock %}

{% block content %}

<div class="container p-3 mt-3">
    <div class="row">
        <div class="col-md-6">
            <img src="{{product.image}}" class="card-img-top" alt="product image">
        </div>
        <div class="col-md-6">
            <div class="display-5 mb-3">{{product.name}}</div>
            <div class="display-6 mb-3 text-success">Price: ${{product.price}}</div>
            <div class="display-7 mb-3">Category: {{product.get_category_display}}</div>
            <div class="display-7 mb-3">Seller: {{product.user}}</div>
            <div class="display-8 mb-3">Description: {{product.description}}</div>
            {% if product.user == user %}
                <a class='btn btn-outline-success w-100 mb-3' href="{% url 'product-update' product.id %}" class="btn warn">Edit</a>
                <a class='btn btn-outline-danger w-100 mb-3' href="{% url 'product-delete' product.id %}" class="btn danger">Delete</a>
            {% else %}
                {% if product.status == False %}
                    <a class='btn btn-outline-warning w-100' href={% url 'order-confirm' product.id %}>Place your Order</a>
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

purplegorilla/templates/purplegorilla/index.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/index.css' %}" />
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    <div class="container p-3">
        <div class="row">
            {% for product in products %}
                <div class="col-md-3 mb-3">
                    <div class="card">
                        <img src="{{product.image}}" style="height: 300px; object-fit: cover;" alt="product image">
                        <div class="card-body">
                            <div class="card-title">
                                <a class='product-link w-100' href="{% url "product-detail" product.id %}">
                                    Name: {{product.name}}
                                </a>
                            </div>
                            <div class="card-text">
                                <div>Seller: {{product.user}}</div>
                                <div>Price: ${{product.price}}</div>
                                <div class='product-detail'>Description: {{product.description}}</div>
                                <div>Category: {{product.get_category_display}}</div>
                            </div>
                            {% if user != product.user %}
                                <a class="btn btn-outline-primary w-100 my-3" href='{% url "order-confirm" product.id %}'>Purchase Item</a>
                            {% else %}
                                <a class="btn btn-outline-danger w-100 my-3" href='{% url "product-delete" product.id %}'>Remove Listing</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {%endfor%}
        </div>
    </div>
{% endif %}
{% endblock %}

purplegorilla/templates/purplegorilla/order_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container p-3 mt-3">
    <div class="row">
        <div class="col-md-6">
            <h1>Order Details</h1>
            <div class="card mb-3">
                <div class="row g-0">
                  <div class="col-md-4">
                    <img src="{{order.product.image}}" class="img-fluid rounded-start" alt="...">
                  </div>
                  <div class="col-md-8">
                    <div class="card-body">
                      <h5 class="card-title">Name: {{order.product.name}}</h5>
                      <p class="card-text"> Price: {{order.product.price}}</p>
                      <p class="card-text"> Description: {{order.product.description}}</p>
                      <p class="card-text"><small class="text-body-secondary">Sold by: {{order.product.user.username}}</small></p>
                    </div>
                  </div>
                </div>
            </div>
            <h1>Order Summary</h1>
            <table class="table">
                <tbody>
                  <tr>
                    <td>Items:</td>
                    <td>${{order.product.price}}</td>
                  </tr>
                  <tr>
                    <td>Shipping and Handling:</td>
                    <td>$10.00</td>
                  </tr>
                  <tr>
                    <td>Total before Tax:</td>
                    <td>${{oder.product.total_before_tax|floatformat:2}}</td>
                  </tr>
                  <tr>
                    <td>Estimated tax to be collected:</td>
                    <td>${{order.product.estimated_tax|floatformat:2 }}</td>
                  </tr>
                  <tr>
                    <td class='h3'>Order Total:</td>
                    <td class='h3'>${{order.product.total_price|floatformat:2}}</td>
                  </tr>
                </tbody>
            </table>
            <h1>Order Status: {{order.status}}</h1>
        </div>
        <div class="col-md-6">
            <div class="display-5 mb-3 text-center">Are you sure you want to cancel this order?</div>
    
            <form action="" method="post" class="form">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger w-100 mb-3">Yes - Cancel!</button>
                <a href="{% url 'order-detail' order.id %}" class="btn btn-outline-secondary w-100">Cancel</a>
            </form> 
        </div>
    </div>
</div>
{% endblock %}

purplegorilla/templates/purplegorilla/order_form.html
{% extends 'base.html' %}
{% load static %}
{% load form_tags %}

{% block head %}
{% endblock %}

{% block content %}
    <form action="" method="post" class='w-50 mx-auto mt-5 border rounded p-4'>
        {% csrf_token %}
        {% if order %}
        <h1 class='text-center'>Update Order Status</h1>
        {% endif %}
        <div class="mb-3">
            <label for="id_status" class="form-label">Status</label>
            {{ form.status|add_class:"form-select" }}
        </div>
        <button type="submit" class="btn btn-outline-primary w-100">Submit!</button>
    </form>
{% endblock %}

purplegorilla/templates/purplegorilla/product_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container p-3 mt-3">
    <div class="row">
        <div class="col-md-6">
            <div class="card border border-0">
                <img src="{{product.image}}" alt="product image">
                <div class="card-body">
                    <div class="card-title">
                        <a class='product-link w-100' href="{% url "product-detail" product.id %}">
                            Name: {{product.name}}
                        </a>
                    </div>
                    <div class="card-text">
                        <div>Seller: {{product.user}}</div>
                        <div>Price: ${{product.price}}</div>
                        <div class='product-detail'>Description: {{product.description}}</div>
                        <div>Category: {{product.get_category_display}}</div>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-md-6">
            <div class="display-5 mb-3 text-center">Are you sure you want to delete this product?</div>
    
            <form action="" method="post" class="form">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger w-100 mb-3">Yes - Delete!</button>
                <a href="{% url 'product-detail' product.id %}" class="btn btn-outline-secondary w-100">Cancel</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

purplegorilla/templates/purplegorilla/product_form.html
{% extends 'base.html' %}
{% load static %}
{% load form_tags %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %}

{% block content %}
    <form action="" method="post" class='w-50 mx-auto mt-5 border rounded p-4'>
        {% csrf_token %}
        {% if product %}
        <h1 class='text-center'>Edit Product</h1>
        {% else %}
        <h1 class='text-center'>Sell a Product</h1>
        {% endif %}
        <div class="mb-3">
            <label for="id_name" class="form-label">Name</label>
            {{ form.name|add_class:"form-control" }}
        </div>

        <div class="mb-3">
            <label for="id_image" class="form-label">Image</label>
            {{ form.image|add_class:"form-control" }}
        </div>

        <div class="mb-3">
            <label for="id_description" class="form-label">Description</label>
            {{ form.description|add_class:"form-control" }}
        </div>

        <div class="mb-3">
            <label for="id_category" class="form-label">Category</label>
            {{ form.category|add_class:"form-select" }}
        </div>

        <div class="mb-3">
            <label for="id_price" class="form-label">Price</label>
            {{ form.price|add_class:"form-control" }}
        </div>
        <button type="submit" class="btn btn-outline-primary w-100">Submit!</button>
    </form>
{% endblock %}

purplegorilla/templates/user.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/index.css' %}" />
{% endblock %}

{% block content %}

{% if user.is_authenticated %}
    <div class="container my-3">
        <h1 class='text-center'>My Listings</h1>
        <div class="row">
            {% for product in products %}
                {% if product.status == False %}
                    <div class="col-md-3 mb-3">
                        <div class="card">
                            <img src="{{product.image}}" class="card-img-top" style="height: 300px; object-fit: cover;" alt="Product Image">
                            <div class="card-body">
                                <div class="card-title">
                                    Name: 
                                    <a class='product-link w-100 d-inline' href="{% url "product-detail" product.id %}">
                                        {{product.name}}
                                    </a>
                                </div>
                                <div class="card-text">
                                    <div>Seller: {{product.user}}</div>
                                    <div>Price: ${{product.price}}</div>
                                    <div class='product-detail'>Description: {{product.description}}</div>
                                    <div>Category: {{product.get_category_display}}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {%endfor%}
        </div>
    </div>
    <div class="container my-3">
        <h1 class='text-center'>Order Manager</h1>
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Order ID</th>
                <th scope="col">Order Placed</th>
                <th scope="col">Ship To</th>
                <th scope="col">Product Name</th>
                <th scope="col">Status</th>
                <th scope="col">Update Order Status</th>
                <th scope="col">Cancel Order</th>
                <th scope="col">Total</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders%}
                    {% if order.product.status == True and order.user != user %}
                        <tr>
                            <th scope="row">
                                <a href={% url 'order-detail' order.id %}>{{order.id}}</a>
                            </th>
                            <td>{{order.created_at}}</td>
                            <td>{{order.user}}</td>
                            <td>
                                <a href="{% url "product-detail" order.product.id %}">
                                    {{order.product.name}}
                                </a>
                            </td>
                            <td>{{order.status}}</td>
                            <td >
                                <a href="{% url 'order-update' order.id %}">
                                    <i class="bi bi-pencil-square text-success text-center"></i>
                                </a>
                            </td>
                            <td>
                                <a href={% url 'order-delete' order.id %}>
                                    <i class="bi bi-x-square-fill text-danger"></i>
                                </a>
                            </td>
                            <td>{{order.total_price}}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="container">
        <h1 class='text-center'>Purchase History</h1>
        <table class="table">
            <thead>
              <tr>
                <th scope="col">Order ID</th>
                <th scope="col">Order Placed</th>
                <th scope="col">Ship From</th>
                <th scope="col">Product Name</th>
                <th scope="col">Status</th>
                <th scope="col">Total</th>
              </tr>
            </thead>
            <tbody>
                {% for order in orders%}
                    {% if order.user == user %}
                        <tr>
                            <th scope="row">
                                <a href={% url 'order-detail' order.id %}>{{order.id}}</a>
                            </th>
                            <td>{{order.created_at}}</td>
                            <td>{{order.product.user}}</td>
                            <td class='w-50'>
                                <a href="{% url "product-detail" order.product.id %}">
                                    {{order.product.name}}
                                </a>
                            </td>
                            <td>{{order.status}}</td>
                            <td>{{order.total_price}}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}
{% endblock %}